#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-am-common-wfs-ui.service-account.name" . }}
  annotations: {{- include "eric-am-common-wfs-ui.annotations" . | nindent 4 }}
  labels: {{- include "eric-am-common-wfs-ui.labels.extended-defaults" . | nindent 4 }}
automountServiceAccountToken: false