#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

ARG BASE_IMAGE_VERSION
FROM armdocker.rnd.ericsson.se/proj-am/sles/sles-corretto-openjdk17:${BASE_IMAGE_VERSION}

COPY ./eric-am-common-wfs-ui-testware/target/*.jar /app/stubs.jar

RUN chmod 777 /app/stubs.jar

WORKDIR /app

ENTRYPOINT ["java", "-jar", "/app/stubs.jar"]
