#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: eric-am-onboarding-service
  annotations: {{- include "eric-am-common-wfs-ui-dev-backend.annotations" . | nindent 4 }}
  labels: {{- include "eric-am-common-wfs-ui-dev-backend.labels.extended-defaults" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 10102
      protocol: TCP
      name: onboarding
  selector:
    app: {{ template "eric-am-common-wfs-ui-dev-backend.name" . }}
    release: {{ .Release.Name }}
