#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: eric-oss-system-user-secret
  annotations: {{- include "eric-am-common-wfs-ui-dev-backend.annotations" . | nindent 4 }}
type: Opaque
data:
  system-user: {{ index .Values "system-user" "credentials" "username" | b64enc | quote }}
  system-user-pwd: {{ index .Values "system-user" "credentials" "password" | b64enc | quote }}