#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: eric-eo-database-pg-secret
  annotations: {{- include "eric-am-common-wfs-ui-dev-backend.annotations" . | nindent 4 }}
type: Opaque
data:
  custom-user: {{ index .Values "eric-eo-api-gateway" "db" "username" | b64enc | quote}}
  custom-pwd: {{ index .Values "eric-eo-api-gateway" "db" "password" | b64enc | quote}}
  super-user: {{ index .Values "eric-eo-api-gateway" "db" "superUser" | b64enc | quote}}
  super-pwd: {{ index .Values "eric-eo-api-gateway" "db" "superPassword" | b64enc | quote}}